config/routes.rb
Rails.application.routes.draw do

  resources :searches do
      get 'searches/:q' => 'searches#show'
    end
  resources :characters do
      get 'character/:id' => 'characters#show'
    end
  resources :starships do
      get 'starships/:id' => 'starships#show'
    end
  resources :planets do
        get 'planets/:id' => 'planets#show'
    end
  resources :films do
    get 'films/:id' => 'films#show'
  end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
require 'httparty'
require 'pp'
require 'json'


class CharactersController < ApplicationController
  include Consulta

  def show
    response = HTTParty.get("https://swapi.co/api/people/#{params[:id]}", :headers =>{'Content-Type' => 'application/json'} ).body
    @character = JSON.parse(response)
    @film = consulta(JSON.parse(response)["films"], "title")
    @starship = consulta(JSON.parse(response)["starships"], "name")
    @planet = consulta_planet(JSON.parse(response)["homeworld"], "name")

  end
  end

app/controllers/concerns/consulta.rb
module Consulta
  extend ActiveSupport::Concern
  def consulta(urls, atributo)
      respuesta = []
      urls.each do |url|
          res = HTTParty.get(url, :headers =>{'Content-Type' => 'application/json'} ).body
          char_json = JSON.parse(res)
          tupla = [char_json[atributo], url, get_id(url)]
          respuesta << tupla
      end
      return respuesta
  end

  def consulta_planet(urls, atributo)
          res = HTTParty.get(urls, :headers =>{'Content-Type' => 'application/json'} ).body
          char_json = JSON.parse(res)
          tupla = [char_json[atributo], urls, get_id(urls)]
      return tupla
  end

  def consulta_search(json, atributo)
    listas_url = []
      while json["next"] != nil do
        results = json["results"]
        results.each do |x|
          listas_url << x["url"]
        end
        puts json["next"]
        puts "__________________"
        resp = HTTParty.get(json["next"], :headers =>{'Content-Type' => 'application/json'} ).body
        json = JSON.parse(resp)
      end
    json["results"].each do |x|
        listas_url << x["url"]
      end
    return consulta(listas_url, atributo)
  end



def get_id(url)
  id = url.split("/")[-1]
  return id
end




end

app/controllers/films_controller.rb
require 'httparty'
require 'pp'
require 'json'

class FilmsController < ApplicationController
  include Consulta
  def show
    response = HTTParty.get("https://swapi.co/api/films/#{params[:id]}", :headers =>{'Content-Type' => 'application/json'} ).body
    @film = JSON.parse(response)
    @character = consulta(JSON.parse(response)["characters"], "name")
    @starship = consulta(JSON.parse(response)["starships"], "name")
    @planet = consulta(JSON.parse(response)["planets"], "name")
    puts @character

  end
end

app/controllers/planets_controller.rb
require 'httparty'
require 'pp'
require 'json'


class PlanetsController < ApplicationController
  include Consulta

  def show
    response = HTTParty.get("https://swapi.co/api/planets/#{params[:id]}", :headers =>{'Content-Type' => 'application/json'} ).body
    @planet = JSON.parse(response)
    @film = consulta(JSON.parse(response)["films"], "title")
    @character = consulta(JSON.parse(response)["residents"], "name")
  end


  end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  include Consulta

  def index
    response1 = HTTParty.get("https://swapi.co/api/people/?search=#{params[:q]}", :headers =>{'Content-Type' => 'application/json'} ).body
    @character = consulta_search(JSON.parse(response1), "name")
    response2 = HTTParty.get("https://swapi.co/api/films/?search=#{params[:q]}", :headers =>{'Content-Type' => 'application/json'} ).body
    @film = consulta_search(JSON.parse(response2), "title")
    response3 = HTTParty.get("https://swapi.co/api/planets/?search=#{params[:q]}", :headers =>{'Content-Type' => 'application/json'} ).body
    @planet = consulta_search(JSON.parse(response3), "name")
    response4 = HTTParty.get("https://swapi.co/api/starships/?search=#{params[:q]}", :headers =>{'Content-Type' => 'application/json'} ).body
    @starship = consulta_search(JSON.parse(response4), "name")

  end

  def show

  end
end

app/controllers/starships_controller.rb
require 'httparty'
require 'pp'
require 'json'

class StarshipsController < ApplicationController
  include Consulta
  def show
    response = HTTParty.get("https://swapi.co/api/starships/#{params[:id]}", :headers =>{'Content-Type' => 'application/json'} ).body
    @starship = JSON.parse(response)
    @film = consulta(JSON.parse(response)["films"], "title")
    @character = consulta(JSON.parse(response)["pilots"], "name")

  end
  end

app/controllers/welcome_controller.rb
require 'httparty'
require 'pp'
require 'json'

class WelcomeController < ApplicationController

  def index
    response = HTTParty.get('https://swapi.co/api/films', :headers =>{'Content-Type' => 'application/json'} ).body
    @films = JSON.parse(response)["results"]


    end


  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/starships_helper.rb
module StarshipsHelper
end

app/helpers/welcom_helper.rb
module WelcomHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/characters/index.html.erb
<h1>Characters#index</h1>
<p>Find me in app/views/characters/index.html.erb</p>

<h1>Listing Hotels</h1>
<% if !@characters.blank? %>
<pre><%= JSON.pretty_generate(@characters) %></pre>
<% end %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Star rating</th>
      <th>Accomodation type</th>
    </tr>
  </thead>

  <tbody>

      <tr>
        <td></td>

      </tr>

app/views/characters/show.html.erb
<%= render "searches/index" %>

<h1>Peronaje: <%=@character["name"] %></h1>
<strong>Altura</strong>
<td><%=@character["height"] %></td>
<br>
<strong>Peso</strong>
<td><%=@character["mass"] %></td>
<br>
<strong>Peluca</strong>
<td><%=@character["hair_color"] %></td>
<br>
<strong>Color de Piel</strong>
<td><%=@character["skin_color"] %></td>
<br>
<strong>Color de Ojos</strong>
<td><%=@character["eye_color"] %></td>
<br>
<strong>Fecha de nacimiento</strong>
<td><%=@character["birth_year"] %></td>
<br>
<strong>Sexo</strong>
<td><%=@character["height"] %></td>
<br>
<strong>Planeta</strong>
<td><a href="/planets/<%=@planet[2]%>"><%= @planet[0]%></a><br> </td>

<br>

<table>
  <thead>
    <tr>
      <th>Peliculas:</th>
    </tr>
  </thead>
  <tbody>
    <% @film.each do |f|%>
      <tr>
        <td><%= link_to f[0], film_url(f[2]) %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th>Naves:</th>
    </tr>
  </thead>
  <tbody>
    <% @starship.each do |f|%>
      <tr>
        <td><%= link_to f[0], starship_url(f[2]) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/films/index.html.erb
<h1>Films#index</h1>
<p>Find me in app/views/films/index.html.erb</p>


<table>
  <thead>
    <tr>
      <th>Pelicula</th>
      <th>Año</th>
      <th>Numero</th>
      <th>Direstor</th>
      <th>Produstor</th>
    </tr>
  </thead>

  <tbody>
    <% @film do |f|%>
      <tr>
        <td><a href="/films/<%=f["id"]%>"><%= f["title"] %></a><br> </td>
        <td><%=f["release_date"] %></td>
        <td><%= f[ "episode_id"] %></td>
        <td><%= f["director"] %></td>
        <td><%= f["producer"] %></td>
        <%= puts f["id"] %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/films/show.html.erb
<%= render "searches/index" %>

<div class='panel panel-default'>
  <div class="panel-heading"><h1 class='text-center'><%= @film["title"] %></h1></div>
  <table class='table table-bordered'>
    <tr>
      <th>Director:</th>
      <td><%=@film["director"]%></td>
    </tr>
    <tr>
      <th>Producer:</th>
      <td><%= @film["producer"] %>kg</td>
    </tr>
  </table>
  <div class="panel-heading"><h5 class='text-center'>Opening Crawl</h5></div>
  <div class="panel-body">
     <p><%= @film["opening_crawl"] %></p>
   </div>
</div>

<table>
  <thead>
    <tr>
      <th>Personaje</th>
    </tr>
  </thead>
  <tbody>
    <% @character.each do |c|%>
      <tr>
        <td><%= link_to c[0], character_url(c[2]) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Planetas</th>
    </tr>
  </thead>
  <tbody>
    <% @planet.each do |p|%>
      <tr>
        <td><%= link_to p[0], planet_url(p[2]) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Naves</th>
    </tr>
  </thead>
  <tbody>
    <% @starship.each do |s|%>
      <tr>
        <td><%= link_to s[0], starship_url(s[2]) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WindowsBashTestApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/planets/index.html.erb
<h1>Planets#index</h1>
<p>Find me in app/views/planets/index.html.erb</p>

app/views/planets/show.html.erb
<%= render "searches/index" %>

<h1>Peronaje: <%=@planet["name"] %></h1>
<strong>Periodo de rotación:</strong>
<td><%=@planet["rotation_period"] %></td>
<br>
<strong>Periodo Orbital:</strong>
<td><%=@planet["orbital_period"] %></td>
<br>
<strong>Diametro:</strong>
<td><%=@planet["diameter"] %></td>
<br>
<strong>Clima:</strong>
<td><%=@planet["climate"] %></td>
<br>
<strong>Gravedad</strong>
<td><%=@planet["gravity"] %></td>
<br>
<strong>Terreno</strong>
<td><%=@planet["terrain"] %></td>
<br>
<strong>Superficie de agua</strong>
<td><%=@planet["surface_water"] %></td>
<br>
<strong>Poblacion</strong>
<td><%=@planet["population"] %></td>
<br>

<table>
  <thead>
    <tr>
      <th>Residentes:</th>
    </tr>
  </thead>
  <tbody>
    <% @character.each do |c|%>
      <tr>
        <td><%= link_to c[0], character_url(c[2]) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Peliculas:</th>
    </tr>
  </thead>
  <tbody>
    <% @film.each do |f|%>
      <tr>
        <td><%= link_to f[0], film_url(f[2]) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/searches/_index.html.erb
<%= form_tag("/searches", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/searches/index.html.erb
<%= render "index" %>

<h1>Resultado de busqueda</h1>

<table>
  <thead>
    <tr>
      <th>Personajes:</th>
    </tr>
  </thead>
  <tbody>
    <% @character.each do |c|%>
      <tr>
        <td><%= link_to c[0], character_url(c[2]) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Peliculas:</th>
    </tr>
  </thead>
  <tbody>
    <% @film.each do |f|%>
      <tr>
        <td><%= link_to f[0], film_url(f[2]) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Panetas:</th>
    </tr>
  </thead>
  <tbody>
    <% @planet.each do |f|%>
      <tr>
        <td><%= link_to f[0], planet_url(f[2]) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Naves:</th>
    </tr>
  </thead>
  <tbody>
    <% @starship.each do |f|%>
      <tr>
        <td><%= link_to f[0], starship_url(f[2]) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>

<%= link_to 'Volver', :back %>

app/views/searches/show.html.erb
<%= render "index" %>

<h1>Busqueda: </h1>

app/views/starships/index.html.erb
<h1>Starships#index</h1>
<p>Find me in app/views/starships/index.html.erb</p>

app/views/starships/show.html.erb
<%= render "searches/index" %>

<h1>Nave: <%=@starship["name"] %></h1>

<strong>Modelo:</strong>
<td><%=@starship["model"] %></td>
<br>
<strong>Crado por:</strong>
<td><%=@starship["manufacturer"] %></td>
<br>
<strong>Costo:</strong>
<td><%=@starship["cost_in_credits"] %></td>
<br>
<strong>Largo:</strong>
<td><%=@starship["climate"] %></td>
<br>
<strong>Velocidad Máxima:</strong>
<td><%=@starship["max_atmosphering_speed"] %></td>
<br>
<strong>Tripulación:</strong>
<td><%=@starship["crew"] %></td>
<br>
<strong>Pasajeros:</strong>
<td><%=@starship["passengers"] %></td>
<br>
<strong>Capacidad de Carga:</strong>
<td><%=@starship["cargo_capacity"] %></td>
<br>
<strong>Consumo</strong>
<td><%=@starship["consumables"] %></td>
<br>
<strong>Hyperdive rating</strong>
<td><%=@starship["hyperdrive_rating"] %></td>
<br><strong>MGLT</strong>
<td><%=@starship["MGLT"] %></td>
<br><strong>Clase: </strong>
<td><%=@starship["starship_class"] %></td>

<br>

<table>
  <thead>
    <tr>
      <th>Pilotos:</th>
    </tr>
  </thead>
  <tbody>
    <% @character.each do |c|%>
      <tr>
        <td><%= link_to c[0], character_url(c[2]) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Peliculas:</th>
    </tr>
  </thead>
  <tbody>
    <% @film.each do |f|%>
      <tr>
        <td><%= link_to f[0], film_url(f[2]) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/welcome/index.html.erb
<h1>API STARWARS</h1>

<%= render "searches/index" %>


<table>
  <thead>
    <tr>
      <th>Pelicula</th>
      <th>Año</th>
      <th>Numero</th>
      <th>Director</th>
      <th>Productor</th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |f|%>
      <tr>
        <td><a href="/films/<%=f["url"].split("/")[-1]%>"><%= f["title"] %></a><br> </td>
        <td><%=f["release_date"] %></td>
        <td><%= f[ "episode_id"] %></td>
        <td><%= f["director"] %></td>
        <td><%= f["producer"] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>